name: Build and Test

# Simple build verification - let Vercel handle deployment automatically
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate version info
      run: npm run prebuild

    - name: Build application
      run: npm run build

    - name: Run tests (optional)
      run: npm run test:run || echo "No tests configured"
      
    - name: Build Success
      run: echo "✅ Build completed successfully! Vercel will deploy automatically."
